# Generated by Django 3.0 on 2019-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=4)),
            ],
        ),
    ]
