# Generated by Django 3.0 on 2019-12-04 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='year',
        ),
    ]
