# Generated by Django 3.0 on 2019-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0002_remove_cars_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
