# Generated by Django 3.0 on 2019-12-10 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0004_auto_20191210_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sellers',
        ),
    ]
