# Generated by Django 3.0 on 2019-12-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seller', '0001_initial'),
        ('car', '0005_delete_sellers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='seller.Sellers'),
        ),
    ]
