# Generated by Django 3.0 on 2019-12-10 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0006_cars_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='seller',
        ),
    ]
