# Generated by Django 3.0 on 2019-12-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('seller', '0001_initial'),
        ('car', '0008_cars_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='seller',
            field=models.ForeignKey(default='Private', on_delete=django.db.models.deletion.CASCADE, to='car.Sellers'),
        ),
    ]
