# Generated by Django 3.0 on 2019-12-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0011_auto_20191211_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='veryfied',
            field=models.CharField(default='Yes', max_length=3),
            preserve_default=False,
        ),
    ]
