# Generated by Django 3.0 on 2019-12-12 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0012_car_veryfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='veryfied',
        ),
    ]
